name: 'Bump Version'
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - edited
      - ready_for_review
      - labeled
      - reopened

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: 'actions/checkout@v3'
      - name: Pull Request Version Bump
        id: bump
        uses: fadi-quader-mox/pr-version-bump@v1.0.0
        with:
          GITHUB_TOKEN: ${{ github.token }}

  remove-labels:
    runs-on: ubuntu-latest
    needs: bump-version
    if: ${{ github.event_name }} == 'workflow_run' && ${{ github.workflow }} == 'Bump Version' && ${{ github.workflow.conclusion }} == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm i -D @actions/core @actions/github @octokit/action axios
      # Node.js script can be anywhere. A good convention is to put local GitHub Actions
      # into the `.github/actions` folder
      - name: Remove label
        run: |
          const { Octokit } = require('@octokit/action');
          const axios = require('axios');
          const octokit = new Octokit({ auth: ${{github.token}} });
    env:
      GITHUB_TOKEN: ${{ github.token }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.repository }}
      issue: ${{ github.event.number }}
      label: ${{ github.event.label.name }}
